name: Autograding Tests
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        id: npm-test
        run: npm test

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          NPM-TEST_RESULTS: "${{ steps.npm-test.outputs.result }}"
        with:
          runners: npm-test
